name: Publish to npmjs

on:
  push:
    tags:
      - v*

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11
          run_install: false

      - uses: actions/setup-node@v6
        with:
          node-version: '26'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm i && pnpm publish --no-git-checks
